# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 00:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2016, 2, 22, 0, 43, 55, 142470, tzinfo=utc)),
        ),
    ]
